services:
  main-db:
    env_file:
      - path: ./db/default.env
        required: true
    ports:
      - "5432:5432"
    build: 
      dockerfile: db/dockerfile
    volumes:
      - pgdata:/var/lib/postgresql
      
volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db/data